import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { Footer } from '../components/layout/Footer'
import { Header } from '../components/layout/Header'

export function TermsPage() {
  useEffect(() => { document.title = 'Terms of Use | Peptis'; window.scrollTo(0, 0) }, [])
  return (
    <div className="site"><Header variant="quiz" /><main className="notice-page"><section className="section"><div className="notice-inner">
      <p className="eyebrow">Legal</p><h1>Terms of Use</h1><p className="notice-updated">Effective: September 16, 2026</p>
      <p>These Terms govern your use of peptis.com and the programmes, planning tools, educational content, coaching, training resources, supplements and other non-clinical products and services offered by Information Edge Insights LLC, a Wyoming limited liability company trading as Peptis (“Peptis,” “we,” “us”). By using the Services or affirmatively accepting these Terms, you agree to them and our <Link to="/privacy">Privacy Policy</Link> and applicable supplemental terms.</p>
      <h2>1. Eligibility and accounts</h2><p>You must be at least 18 and legally capable of entering a contract. Information you provide must be accurate and current. You are responsible for safeguarding account credentials and activity under your account.</p>
      <h2>2. What Peptis provides</h2><p>Peptis provides wellness, coaching, nutrition-planning, exercise and body-composition support for adults using or transitioning from GLP-1 therapy. Features and availability may vary by location and release stage. We may modify or discontinue features where reasonably necessary.</p>
      <h2>3. Not medical care</h2><p>Unless you are interacting directly with a separately identified licensed clinical provider, Peptis coaching, quizzes, training plans, nutrition information, supplement information and educational content are not medical advice, diagnosis or treatment and do not create a clinician-patient relationship. Do not use Peptis for emergencies. For an emergency, contact 911 or the appropriate local emergency service.</p>
      <h2>4. Clinical and telehealth services</h2><p>Clinical services, if and when activated in an eligible state, are provided by independent or contracted licensed clinical providers using third-party telehealth infrastructure. Information Edge Insights LLC is not itself a medical practice. Eligibility, diagnosis, treatment and prescribing decisions belong to the treating licensed provider. No consultation, prescription, medication or particular outcome is guaranteed. Separate provider terms, privacy notices, informed consent and fees may apply.</p>
      <h2>5. Supplements and products</h2><p>Peptis may sell or facilitate fulfilment of dietary supplements and wellness products. Supplements are not medications and are not intended to diagnose, treat, cure or prevent disease or medication side effects. Product labels, directions, warnings and ingredient information should be reviewed before use. Consult an appropriate healthcare professional before using supplements if you have a medical condition, take medication, are pregnant or nursing, or have questions about interactions. Product availability and formulations may change.</p>
      <h2>6. Coaching and training</h2><p>Coaches provide education, accountability and general wellness support and are not acting as physicians, dietitians or other licensed clinicians unless expressly identified as such for a specific service. Exercise involves inherent risk. You are responsible for choosing appropriate activities and stopping and seeking professional advice if you experience concerning symptoms.</p>
      <h2>7. Purchases, pricing and subscriptions</h2><p>Prices and the material terms of any purchase or subscription will be shown before checkout. Taxes, shipping and other disclosed charges may apply. If we offer an automatically renewing subscription, the checkout flow will disclose the billing interval, recurring price and cancellation method before you agree. We will not charge a founding reservation unless the checkout expressly states otherwise. Refund, cancellation and fulfilment terms presented at purchase form part of these Terms.</p>
      <h2>8. Third-party services</h2><p>Peptis may rely on payment processors, fulfilment providers, analytics providers, hosting providers, telehealth vendors and other third parties. Their services may be governed by separate terms. Peptis is not responsible for third-party services outside our reasonable control, subject to applicable law.</p>
      <h2>9. Privacy and health information</h2><p>Our <Link to="/privacy">Privacy Policy</Link> explains how Peptis handles personal information. Our <Link to="/health-data">Consumer Health Data Notice</Link> provides additional information for consumer health data covered by applicable state laws. Clinical providers may issue separate privacy notices governing information used for medical care.</p>
      <h2>10. Acceptable use</h2><p>You may not misuse the Services; interfere with security or operation; attempt unauthorized access; scrape or harvest data except as permitted by law; upload malicious code; impersonate another person; use the Services unlawfully; or reproduce, resell or exploit Peptis content or software except as expressly permitted.</p>
      <h2>11. Intellectual property</h2><p>Peptis and its licensors retain all rights in the Services, software, designs, text, graphics, branding and other content. Subject to these Terms, we grant you a limited, revocable, non-exclusive, non-transferable license to use the Services for personal, non-commercial purposes.</p>
      <h2>12. User submissions and feedback</h2><p>You retain rights you have in content you submit. You grant Peptis the rights reasonably necessary to host, process and use that content to provide, secure and improve the Services in accordance with our Privacy Policy. Feedback and suggestions may be used without compensation or obligation, provided we do not publicly identify you without permission.</p>
      <h2>13. No guaranteed outcomes</h2><p>Health, weight, strength, body-composition and adherence outcomes vary. Testimonials, examples, projections and educational material do not guarantee individual results. Peptis does not guarantee that a programme, product or future clinical pathway will be suitable or available for every person.</p>
      <h2>14. Disclaimers</h2><p>To the maximum extent permitted by law, the Services are provided “as is” and “as available.” We disclaim implied warranties to the extent legally permitted. Nothing in these Terms excludes warranties or consumer rights that cannot lawfully be excluded.</p>
      <h2>15. Limitation of liability</h2><p>To the maximum extent permitted by law, Information Edge Insights LLC will not be liable for indirect, incidental, special, consequential or punitive damages, or loss of profits or data, arising from the Services. Our aggregate liability for claims arising from a paid Peptis service will not exceed the greater of the amount you paid Peptis for that service during the 12 months preceding the event giving rise to the claim or $100. These limits do not apply where prohibited by law or to liability that cannot lawfully be limited.</p>
      <h2>16. Indemnification</h2><p>To the extent permitted by law, you agree to indemnify Information Edge Insights LLC against third-party claims arising from your unlawful misuse of the Services or material breach of these Terms. This does not require you to indemnify us for our own negligence, misconduct or violations of law.</p>
      <h2>17. Suspension and termination</h2><p>We may suspend or terminate access where reasonably necessary for security, fraud prevention, legal compliance, non-payment or material violation of these Terms. You may stop using the Services at any time, subject to any purchase or cancellation terms already agreed.</p>
      <h2>18. Governing law and disputes</h2><p>These Terms are governed by the laws of the State of Wyoming, without regard to conflict-of-laws principles, except where applicable consumer law requires otherwise. Before filing a claim, you and Peptis agree to make a good-faith attempt to resolve the dispute informally by written notice. We have intentionally not inserted mandatory arbitration or a class-action waiver into these Terms without separate legal review.</p>
      <h2>19. Changes</h2><p>We may update these Terms as the Services or law change. Material changes will be communicated as required by law. The effective date above identifies the current version.</p>
      <h2>20. Contact</h2><p>Information Edge Insights LLC, trading as Peptis. Legal questions may be sent to <a href="mailto:legal@peptis.com">legal@peptis.com</a>. Privacy requests should be sent to <a href="mailto:privacy@peptis.com">privacy@peptis.com</a>.</p>
    </div></section></main><Footer /></div>
  )
}
